### ISSUE TITLE
Vignettes quality

### ISSUE THREAD

**Issue by caravagn** [caravagnalab/TAPACLOTH#2]
Still poor in terms of description quality and general logic, language need some polishing too. Do link me here once you have improced those, before closing this issue.

**Comment by caravagn** [comment]
- `devtools::document()` says that examples are missing;
- `pkgdown::build_site()` reports YAML warnings;
- there were things repeated across vignettes (opening parts) that did not make sense, I made a special vignette [TAPACLOTH.Rmd]
- I don't understand the columns `purity` and `sample` are repeated
- S3 methods can be more informative and show nice outputs etc while they do not now.

I don't think this current status is up to our standards yet.

**Comment by caravagn** [comment]
I am pushing to fix these.

**Comment by caravagn** [comment]
All the things are, from a software engineering, really illogical. 

Example: `fit` is sometimes a `tibble`, other times a Bmix object, there is no consistency and well-behaved practices. There have to be uniform SW-practices, otherwise maintaining code is a horrible pain. For instance, how can I run on the same test both the purity estimation and the clonality test?

The current version is close to a spaghetti code.

**Comment by nicola-calonaci** [comment]
OK thanks! I made it such that the output of both `run_classifier` and `estimate purity` is an S3 object of class TAPACLOTH, that always contain the input data in `data`, possibly with new columns (e.g. `class_binom`, `class_terzile` or `purity_bmix`), and either a `classifier` or a `purity_estimate` object or both. These two contain for example the input paramaters and/or plots and fits. 
Everything should be consistent.

**Comment by caravagn** [comment]
If so, I close the issue.
